### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by SkarletShadows** [Darkhax-Minecraft/Tips#60]
Forge version: 41.0.87
Minecraft: 1.19

    -- MOD tipsmod --
    Details:
	    Caused by 0: java.lang.reflect.InvocationTargetException
		    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		    at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
		    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.87.jar%23169!/:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
    
	    Caused by 1: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ScreenEvent$DrawScreenEvent
		    at net.darkhax.tipsmod.TipsModForgeClient.init(TipsModForgeClient.java:16) ~[Tips-Forge-1.19-6.0.1.jar%23153!/:6.0.1] {re:classloading}
		    at net.darkhax.tipsmod.TipsModForge.<init>(TipsModForge.java:21) ~[Tips-Forge-1.19-6.0.1.jar%23153!/:6.0.1] {re:classloading}
		    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		    at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
		    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.87.jar%23169!/:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
    
	    Mod File: Tips-Forge-1.19-6.0.1.jar
	    Failure message: Tips (tipsmod) has failed to load correctly
		    java.lang.reflect.InvocationTargetException: null
	    Mod Version: 6.0.1
	    Mod Issue URL: https://github.com/Darkhax-Minecraft/Tips/issues
	    Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.ScreenEvent$DrawScreenEvent
    Stacktrace:
	    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	    at net.darkhax.tipsmod.TipsModForgeClient.init(TipsModForgeClient.java:16) ~[Tips-Forge-1.19-6.0.1.jar%23153!/:6.0.1] {re:classloading}
	    at net.darkhax.tipsmod.TipsModForge.<init>(TipsModForge.java:21) ~[Tips-Forge-1.19-6.0.1.jar%23153!/:6.0.1] {re:classloading}
	    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	    at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
	    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.87.jar%23169!/:?] {}
	    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by SkarletShadows** [comment]
The forge version was too high, I apologize!

**Comment by Darkhax** [comment]
There were two different Forge updates that broke a lot of mods. Took a bit but this mod has been updated to work with their updates. Check out 6.1.5 when you're ready to update.
