### ISSUE TITLE
Missing Mod Icon

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Tips#64]
ModMenu is forced to load a default icon because Tips does not supply an icon PNG:

```xml
  <log4j:Event logger="Mod Menu | FabricIconHandler" timestamp="1658468522824" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Invalid mod icon for icon source tipsmod: assets/tipsmod/textures/logo.png]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.nio.file.NoSuchFileException: /assets/tipsmod/textures/logo.png
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at jdk.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:856)
	at jdk.nio.zipfs.ZipPath.newInputStream(ZipPath.java:749)
	at jdk.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:261)
	at java.nio.file.Files.newInputStream(Files.java:160)
	at com.terraformersmc.modmenu.util.mod.fabric.FabricIconHandler.createIcon(FabricIconHandler.java:34)
	at com.terraformersmc.modmenu.util.mod.fabric.FabricMod.getIcon(FabricMod.java:140)
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.bindIconTexture(ModListEntry.java:97)
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.render(ModListEntry.java:53)
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.renderList(ModListWidget.java:227)
	at net.minecraft.client.gui.widget.EntryListWidget.render(EntryListWidget:219)
	at com.terraformersmc.modmenu.gui.ModsScreen.render(ModsScreen.java:280)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:877)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
]]></log4j:Throwable>
  </log4j:Event>

actions.js:3142   <log4j:Event logger="Mod Menu | FabricMod" timestamp="1658468522826" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[Warning! Mod tipsmod has a broken icon, loading default icon]]></log4j:Message>
  </log4j:Event>
```

Ignore the XML, it's just a byproduct of the GDLauncher log system.

**Comment by Darkhax** [comment]
Thanks, this issue should be fixed in the latest 1.18.2 update. The fix will also be coming to 1.19+ soon.
