### ISSUE TITLE
fail to load on 1.19 forge 41.1.0

### ISSUE THREAD

**Issue by babacon88** [Darkhax-Minecraft/Tips#68]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 13/8/22, 7:33 pm
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.1.0-universal.jar%23204!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.1.0-universal.jar%23204!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixin.cleancut.json:MinecraftMixin,pl:mixin:APP:the_bumblezone.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:596) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixin.cleancut.json:MinecraftMixin,pl:mixin:APP:the_bumblezone.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixin.cleancut.json:MinecraftMixin,pl:mixin:APP:the_bumblezone.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixin.cleancut.json:MinecraftMixin,pl:mixin:APP:the_bumblezone.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23199!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.1.0.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD tipsmod --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23201!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23200!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ScreenEvent$DrawScreenEvent
		at net.darkhax.tipsmod.TipsModForgeClient.init(TipsModForgeClient.java:16) ~[Tips-Forge-1.19-6.0.1.jar%23183!/:6.0.1] {re:classloading}
		at net.darkhax.tipsmod.TipsModForge.<init>(TipsModForge.java:21) ~[Tips-Forge-1.19-6.0.1.jar%23183!/:6.0.1] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23201!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23200!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /E:/Program Files (x86)/.minecraft/mods/Tips-Forge-1.19-6.0.1.jar
	Failure message: Tips (tipsmod) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 6.0.1
	Mod Issue URL: https://github.com/Darkhax-Minecraft/Tips/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.ScreenEvent$DrawScreenEvent
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at net.darkhax.tipsmod.TipsModForgeClient.init(TipsModForgeClient.java:16) ~[Tips-Forge-1.19-6.0.1.jar%23183!/:6.0.1] {re:classloading}
	at net.darkhax.tipsmod.TipsModForge.<init>(TipsModForge.java:21) ~[Tips-Forge-1.19-6.0.1.jar%23183!/:6.0.1] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23201!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23200!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1486656768 bytes (1417 MiB) / 2617245696 bytes (2496 MiB) up to 13824425984 bytes (13184 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f0a
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6589
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 32694.43
	Virtual memory used (MB): 14697.34
	Swap memory total (MB): 16346.29
	Swap memory used (MB): 128.40
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx13180M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.19_HD_U_H9
	OptiFine Build: 20220731-224510
	Render Distance Chunks: 16
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 465.89
	OpenGlRenderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		SkyVillages-1.0.1-1.19-forge-release.jar          |Sky Villages                  |skyvillages                   |1.0.1-1.19-forge    |COMMON_SET|Manifest: NOSIGNATURE
		SlimyBoyos-forge-1.19-5.0.0.1.jar                 |SlimyBoyos                    |slimyboyos                    |5.0.0.1             |COMMON_SET|Manifest: NOSIGNATURE
		RootsClassic-1.19-1.1.28.jar                      |Roots Classic                 |rootsclassic                  |1.19-1.1.28         |COMMON_SET|Manifest: NOSIGNATURE
		zombiehorsespawn_1.19.0-3.2.jar                   |Zombie Horse Spawn            |zombiehorsespawn              |3.2                 |COMMON_SET|Manifest: NOSIGNATURE
		weeping_angels-41.0.5.jar                         |Weeping Angels                |weeping_angels                |41.0.5              |COMMON_SET|Manifest: NOSIGNATURE
		UndergroundVillages-1.19-1.1.1.jar                |Underground Villages Mod      |underground_villages          |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		Shrines-1.19-5.0.0-alpha3.jar                     |Shrines                       |shrines                       |1.19-5.0.0-alpha3   |COMMON_SET|Manifest: NOSIGNATURE
		Galosphere-1.19-1.1.2-Forge.jar                   |Galosphere                    |galosphere                    |1.19-1.1.2          |COMMON_SET|Manifest: NOSIGNATURE
		Tips-Forge-1.19-6.0.1.jar                         |Tips                          |tipsmod                       |6.0.1               |ERROR     |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedcore-1.19-0.4.10.87.jar              |Sophisticated Core            |sophisticatedcore             |1.19-0.4.10.87      |COMMON_SET|Manifest: NOSIGNATURE
		villagernames_1.19.0-3.7.jar                      |Villager Names                |villagernames                 |3.7                 |COMMON_SET|Manifest: NOSIGNATURE
		Structory-1.19-1.2.jar                            |Structory                     |structory                     |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.26.1_Forge_1.19.jar              |Xaero's World Map             |xaeroworldmap                 |1.26.1              |COMMON_SET|Manifest: NOSIGNATURE
		EnhancedVisuals_FORGE_v1.5.8_mc1.19.jar           |EnhancedVisuals               |enhancedvisuals               |1.5.8               |COMMON_SET|Manifest: NOSIGNATURE
		Tumbleweed-forge-1.19-0.5.1.jar                   |Tumbleweed                    |tumbleweed                    |0.5.1               |COMMON_SET|Manifest: NOSIGNATURE
		SereneSeasons-1.19-8.0.0.19.jar                   |Serene Seasons                |sereneseasons                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		badpackets-forge-0.1.2.jar                        |Bad Packets API               |badpackets                    |0.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		wooltostring-forge-1.19-v1.0.3.jar                |Wool-to-String                |wooltostring                  |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		spawnermod-1.19.0-1.9.1+Forge.jar                 |Enhanced Mob Spawners         |spawnermod                    |1.9.1               |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19-14.2.10.jar                  |Bookshelf                     |bookshelf                     |14.2.10             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		More+Babies-forge-1.19-0.5.3.jar                  |More Babies                   |more_babies                   |0.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.19-3.18.9.661.jar        |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19-3.18.9.661     |COMMON_SET|Manifest: NOSIGNATURE
		snowundertrees-1.19-1.2.2.jar                     |Snow Under Trees              |snowundertrees                |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		Rex's-AdditionalStructures-1.19-(v.4.0.1).jar     |Additional Structures         |additionalstructures          |4.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		SimplyHouses-1.1.3-1.19-forge.jar                 |Simply Houses                 |simply_houses                 |1.1.3.1-1.19        |COMMON_SET|Manifest: NOSIGNATURE
		WaterStrainer-1.19-14.1.1.jar                     |Water Strainer                |waterstrainer                 |1.19-14.1.1         |COMMON_SET|Manifest: NOSIGNATURE
		Terralith_v2.3.3.jar                              |Terralith                     |terralith                     |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		blueprint-1.19-6.0.6.jar                          |Blueprint                     |blueprint                     |6.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		boatload-1.19-4.1.0.jar                           |Boatload                      |boatload                      |4.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19-41.1.0-universal.jar                   |Forge                         |forge                         |41.1.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Waddles-1.19-0.9.1.jar                            |Waddles                       |waddles                       |1.19-0.9.1          |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.19-2.0.12.jar                   |Supplementaries               |supplementaries               |1.19-2.0.12         |COMMON_SET|Manifest: NOSIGNATURE
		neapolitan-1.19-4.0.0.jar                         |Neapolitan                    |neapolitan                    |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		structure_gel-1.19-2.5.4.jar                      |Structure Gel API             |structure_gel                 |2.5.4               |COMMON_SET|Manifest: NOSIGNATURE
		corpse-1.19-1.0.7.jar                             |Corpse                        |corpse                        |1.19-1.0.7          |COMMON_SET|Manifest: NOSIGNATURE
		TinySkeletons-v4.0.0-1.19-Forge.jar               |Tiny Skeletons                |tinyskeletons                 |4.0.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		cleancut-mc1.19-4.2-forge.jar                     |Clean Cut                     |cleancut                      |4.2                 |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19-2.0.0.120.jar             |TerraBlender                  |terrablender                  |2.0.0.120           |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.19-2.0.14.jar                         |Moonlight Library             |moonlight                     |1.19-2.0.14         |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.7.4_mc1.19.jar              |CreativeCore                  |creativecore                  |2.7.4               |COMMON_SET|Manifest: NOSIGNATURE
		CNB-1.19-1.3.4.jar                                |Creatures and Beasts          |cnb                           |1.3.4               |COMMON_SET|Manifest: NOSIGNATURE
		unstructured-0.5.2[FORGE].jar                     |Unstructured [FORGE]          |unstructured                  |0.5.2               |COMMON_SET|Manifest: NOSIGNATURE
		corail_woodcutter-1.19-2.4.2.jar                  |Corail Woodcutter             |corail_woodcutter             |2.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.0.8.jar                  |Croptopia                     |croptopia                     |2.0.8               |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.19.0-4.30.jar                        |Collective                    |collective                    |4.30                |COMMON_SET|Manifest: NOSIGNATURE
		Snow_Pig-1.19-5.0.0.jar                           |Snow Pig                      |snowpig                       |1.19-5.0.0          |COMMON_SET|Manifest: NOSIGNATURE
		sit-1.19-1.3.3.jar                                |Sit                           |sit                           |1.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		vanilla_degus-1.19-v1.3.1-forge.jar               |Vanilla Degus                 |vanilla_degus                 |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		villagertools-1.19-1.0.3.jar                      |villagertools                 |villagertools                 |1.19-1.0.3          |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		ToughAsNails-1.19-8.0.0.78.jar                    |Tough As Nails                |toughasnails                  |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v4.0.18-1.19-Forge.jar                 |Puzzles Lib                   |puzzleslib                    |4.0.18              |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		TrampleStopper-3.6.0-build.32+mc1.19.jar          |Trample Stopper               |tramplestopper                |3.6.0-build.32+mc1.1|COMMON_SET|Manifest: NOSIGNATURE
		the_bumblezone_forge-6.1.6+1.19.jar               |The Bumblezone                |the_bumblezone                |6.1.6+1.19          |COMMON_SET|Manifest: NOSIGNATURE
		Towns-and-Towers-1.19-1.8.1.jar                   |Towns and Towers - Structure A|t_and_t                       |1.8                 |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.16.jar                    |GeckoLib                      |geckolib3                     |3.1.16              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: b885589e-a132-45f7-accf-39f563122e1b
	FML: 41.1
	Forge: net.minecraftforge:41.1.0

**Comment by Darkhax** [comment]
You're using an outdated version of the mod. You can find the latest version [here](https://www.curseforge.com/minecraft/mc-mods/tips/files/3901859)
